version: 0.2
frontend:
  phases:
    pre-build:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    base-directory: build
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
